{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:S256Test", "name": "test_address", "time": 0.06651687622070312, "type": "error", "errtype": "builtins.UnicodeDecodeError", "message": "'ascii' codec can't decode byte 0xc9 in position 3: ordinal not in range(128)", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/pbhacking/addresses-from-keys-jsong-pb-denver-070918/test/index_test.py\", line 17, in test_address\n    point.address(compressed=True, testnet=False), mainnet_address)\n  File \"/home/pbhacking/addresses-from-keys-jsong-pb-denver-070918/index.ipynb\", line 91, in address\n    \"    prefix_m = b'\\\\x00'\\n\",\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 3: ordinal not in range(128)\n"}]}